version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Build Environment
          command: |
            sudo pip install pipenv
            pipenv install  
  test:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            cd ~/project/scripts/tests/
            pipenv run pytest 

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build