version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Build Environment
          command: |
            sudo pip install pipenv
            pipenv install 
            sudo apt-get update 
            sudo apt-get install -y \
                  libhdf5-dev \
                  cmake \
                  gfortran \
                  libblas-dev \
                  liblapack-dev \
                  libeigen3-dev \
                  libhdf5-serial-dev \
                  autoconf \
                  libtool \
                  doxygen \
                  hdf5-tools
            sudo apt-get update
      - run:
          name: Build pyne
          command: |
            mkdir github
            git clone https://github.com/pyne/pyne
            cd pyne/
            pipenv run python setup.py install --user
            nuc_data_make
      - run:
          name: Test
          command: |
            cd ~/project/scripts/tests/
            pipenv run pytest 

workflows:
  version: 2.1
  main:
    jobs:
      - build-and-test
