version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Build Environment
          command: |
            conda install -c anaconda pytest 
      
      
  test:
    executor: python/default
    steps: 
      - checkout   
      - run:
          command: |
            cd ~/project/scripts/tests/
            pytest
          name: Test

workflows:
  main:
    jobs:
      - build